# === Identificación del proyecto ===
sonar.projectKey=CPMBack
sonar.projectName=CPM-Back
sonar.projectVersion=1.0

# === Codificación ===
sonar.sourceEncoding=UTF-8

# === Directorios de código y tests ===
# Analiza todo el proyecto, pero excluye node_modules y carpetas de tests/coverage
sonar.sources=.
sonar.exclusions=node_modules/**,coverage/**, server.js

# Marca dónde están tus pruebas unitarias
sonar.tests=test/
sonar.test.inclusions=**/*.test.js,**/*.spec.js

# === Informes de cobertura ===
# Ajusta la ruta según donde genere tu herramienta (nyc, jest, mocha+nyc…)
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# === Configuración SonarQube server ===
sonar.host.url=http://localhost:9000
sonar.login=squ_6efd621ca44672f59fbe7365b7df2c6b6d7446b1
